language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: CyJSRRfznSnfqZJFzAKz7Ogu2eArNG4gTHxl6vDxIuucY8h78JcUSgvJRWevjsjVppYqf3mRNtuR4gmWBcdc475xbgR7szHBFiQ3ixBrVQyzGls2fPiDkFyEuRQawmWlpOVjXz3jrf/ere9FoK1abFQDBFxoylF+VhIZF1v2eYo=
  - secure: AqO5ZFwDP9DzElmcy4+20BX1lva0YDj/xLLNAFG0vpfx8N9/3Gzt8NyKpmfJQIOIULbrsblywkSrWiOWI1gIz1E4gQ6KDdFNhvw+cbyL2o5toZj0Pfx2ty7r6mkpr4MSQxqSw/t+ZyToq0zmwtbe9R6JGt3teTX5fXHbsWotPg4=
